### ISSUE TITLE
how to visualize skinning weight

### ISSUE THREAD

**Issue by kwea123** [zycliao/skeleton-free-pose-transfer#1]
How to visualize the skinning weight like Figure 3?
Thank you.

**Comment by zycliao** [comment]
I'll add scripts for visualization soon. Basically, we used this [function](https://github.com/zycliao/skeleton-free-pose-transfer/blob/78249f8925fe6a5362f002a0be69d0839bfc5f07/utils/visualization.py#L70). The input argument `score` is the skinning weight and `handle_pos` can be set to `None` if you just want to visualize the skinning weight.

**Comment by kwea123** [comment]
Thank you, I will try

**Comment by kwea123** [comment]
I try to `from utils.visualization import visualize_part`, but it yields this error:
```
ImportError: cannot import name 'mesh_core_cython' from 'utils.render_lib' (/home/kwea123/data/qchen/workspace/skeleton-free-pose-transfer/utils/render_lib/__init__.py)
```
Then I go to `utils.render_lib` and do `python setup.py install` but this time this error:
```
error: /home/kwea123/data/qchen/workspace/skeleton-free-pose-transfer/utils/render_lib/mesh_core_cython.pyx
```
it seems that there is no `mesh_core_cython.pyx` in the folder, which is required to build

**Comment by kwea123** [comment]
The current workaround is to comment out this line
https://github.com/zycliao/skeleton-free-pose-transfer/blob/78249f8925fe6a5362f002a0be69d0839bfc5f07/utils/render.py#L16
and in this case `Pymesh` is **required** in order to color the mesh.

It works after these modifications
<img width="789" alt="スクリーンショット 2022-08-18 12 11 42" src="https://user-images.githubusercontent.com/11364490/185284830-ede1851d-359f-4074-9aa0-041e74e105b4.png">

**Comment by zycliao** [comment]
Good to know you worked it around.
`mesh_core_cython.pyx` has been added in case you need it.
