### ISSUE TITLE
Spikes in ground truth meshes

### ISSUE THREAD

**Issue by sunshineatnoon** [zycliao/skeleton-free-pose-transfer#10]
Hello, thanks for providing the source code.

I followed the [preprocess instructions](https://github.com/zycliao/skeleton-free-pose-transfer#mixamo) to produce testing meshes. I observed that some of the meshes have some spikes (i.e. unsmoothed area) after LBS. Is this normal or did I mess up something in the data processing? Thanks for your time.

<img width="615" alt="Screen Shot 2022-10-23 at 7 18 40 PM" src="https://user-images.githubusercontent.com/7546747/197436065-4892a96d-7eb6-4e29-be62-573a018f4dc9.png">

**Comment by zycliao** [comment]
I'm not sure about it as we didn't find such issues during experiments. If it is a RigNet character, you can check their Github repo, where there're more detailed instructions.
