### ISSUE TITLE
Demo video and motion inputs

### ISSUE THREAD

**Issue by jhonsonlaid** [zycliao/skeleton-free-pose-transfer#11]
Hi, thank you for your great work. I failed to find the asscocicated demo video in the project page, could you publish it? BTW, I'm curious about the outputs quality when inputs are stylized characters with **motion** sequence, are they consecutive or plausible?

**Comment by zycliao** [comment]
Hi, our video has some copyright issues to solve before releasing, but I'm too busy with my graduation recently. Hopefully it can be finished in the next month. If you need it urgently, drop me an email.

When the inputs are motion, there will be some jittering. But with a simple filter on the transformations, the output can be much better. That's also what we did in the video.

**Comment by jhonsonlaid** [comment]
jhonsonlai [at] 126 {DOT} com， thanks.
