### ISSUE TITLE
Mixamo Skinning Weight Ground Truth

### ISSUE THREAD

**Issue by Jayadratha** [zycliao/skeleton-free-pose-transfer#13]
Hi,

To run the ```Mixamo_preprocess_simplify.py```, I need ground truth skinning information of Mixamo characters whose format is like ```rig_info``` from RigNet dataset as you've mentioned in your data preprocessing section. Where can I find them?

Thanks in advance

**Comment by csjxchen** [comment]
I'm looking forward to the reply to this question.

**Comment by zycliao** [comment]
Hi, we converted fbx format of Mixamo to that in `rig_info` by running this [script](https://github.com/zycliao/skeleton-free-pose-transfer/blob/main/data_proc/mixamo_fbx_parser.py) in Maya to get that.
