### ISSUE TITLE
Additional files required for running smpl_simplify.py

### ISSUE THREAD

**Issue by vivekmadhavaram** [zycliao/skeleton-free-pose-transfer#14]
Hello Zycliao,

I do not have lres_up_male.obj and simplify.obj files that are required to run smpl_simplify.py. This part of code is a blocker for the subsequent execution. I am unable to find those files. Can you please help me?

**Comment by zycliao** [comment]
Hi I didn't find those files. But recently I found the processed file simplify.npz (https://drive.google.com/file/d/1plOnfVh0-Et0PFLf5Qf-LFKbmefRJUjD/view?usp=drive_link). Hope this is still useful.
