### ISSUE TITLE
Re-attaching skeleton and weights

### ISSUE THREAD

**Issue by tshrjn** [zycliao/skeleton-free-pose-transfer#16]
Say, I've an asset A with human motion and rig. And another asset B with skeleton, skinning weights, etc.

Now to transfer the motion from A to B via this method, how can I programmatically reattach the rigging (skeleton, skining weights) across the transferred poses/motion?

**Comment by zycliao** [comment]
A possible solution is to first get the animated meshes of A and then run our method from A to B. Now you should have animated meshes of B, with which you can write an optimization, where the supervision is animated meshes of B and the optimization variables are the pose of B.
