### ISSUE TITLE
after downsampling my own smpl mesh file to meet the size, the results are bad

### ISSUE THREAD

**Issue by visonpon** [zycliao/skeleton-free-pose-transfer#4]
Hi @zycliao . thanks for sharing this wonderful work. I have tried to downsampling my own smpl mesh file and use it as the src data, but the results are bad.[I use meshlab to downsampling as you mentioned in this [issue](https://github.com/zycliao/skeleton-free-pose-transfer/issues/2)].  but when I use downsampled mesh as dst and use the src file your provided, the results are normal. 

So how to prepare the pose file for src ? I guess it's becuase the betas parameters of mine smpl files are not the same as your src file?

I wonder if there exist other details that I ignored? hope you can help, thanks~

**Comment by twowwj** [comment]
Did you run the demo.py?

**Comment by zycliao** [comment]
Could you provide your mesh?

**Comment by visonpon** [comment]
I'm sorry it's not convenient for me to upload the mesh file. 
I use the blender smpl add-ons to produce the mesh with setting different pose and shape, and use meshlab to downsampling. it's strange that  those mesh can only use as dst.

**Comment by zycliao** [comment]
Can you check if the body is facing +Z and the head is up to +Y in Meshlab (Blender might change the coordinate system)?

**Comment by visonpon** [comment]
the processed mesh look like this
![2001488824](https://user-images.githubusercontent.com/11517731/188410204-43858cf2-5d72-4b89-8eea-59271e635de4.jpg)

**Comment by visonpon** [comment]
my processed mesh look like below
![2001488824](https://user-images.githubusercontent.com/11517731/188410492-c35e12b0-f3b0-471b-9f26-d8da97b782d5.jpg)

**Comment by visonpon** [comment]
![1746964817](https://user-images.githubusercontent.com/11517731/188411265-2ed7d777-7c68-4d2e-a3b0-4b94e52497cb.jpg)

**Comment by zycliao** [comment]
Can you also show what your `rest.obj` looks like?

**Comment by zycliao** [comment]
Can you also post what your final results look like?

**Comment by visonpon** [comment]
![1982528860](https://user-images.githubusercontent.com/11517731/188415112-ac061f7b-2920-456d-8706-598e12266de8.jpg)

my input and result looks like above, you can see that even T-pose doesn't trans right.
it seems the  root coordinates are zero for your src file  but mine's are not constrained, does this matters?

**Comment by zycliao** [comment]
In the latest commit, I updated a script `demo_smpl.py`, which uses randomly generated SMPL shapes. And the result is as follows
![image](https://user-images.githubusercontent.com/25116439/188438050-a2600fb7-6335-47f0-8d67-5b4e2636e981.png)

**Comment by zycliao** [comment]
Oh, by the way. If you do downsampling, src mesh and rest mesh of src (rest.obj) should have the same triangulation. You can't downsample them separately.

**Comment by visonpon** [comment]
@zycliao ,thanks for your patient responce,  I have tried as you mentioned above, when the src and dst are all from smpl, the results are normal, but when the src from smpl and dst from others like you provided[arissa.obj], the result still looks bad
![1613103659](https://user-images.githubusercontent.com/11517731/188535720-7306ed8f-d556-4306-bd67-f28db672248d.jpg)
what's more the dst1's surface also have some problem.

**Comment by zycliao** [comment]
You can try changing `use_smooth` in the code.

**Comment by jinmelo** [comment]
> Oh, by the way. If you do downsampling, src mesh and rest mesh of src (rest.obj) should have the same triangulation. You can't downsample them separately.

Hi, how to downsample them together with meshlab? It seems the transformation matrix cannot be obtained.

**Comment by zycliao** [comment]
Hi @jinmelo. You can take a look at this https://github.com/zycliao/skeleton-free-pose-transfer/blob/main/utils/mesh_res_mapper.py
First, you downsample one of the meshes, and pass the mesh before and after downsampling to the `__init__` function (v=high res mesh, orig_v=downsampled mesh). Then pass the other high-res mesh to `upsample()`, it will return the downsampled mesh.

**Comment by jinmelo** [comment]
> Hi @jinmelo. You can take a look at this https://github.com/zycliao/skeleton-free-pose-transfer/blob/main/utils/mesh_res_mapper.py First, you downsample one of the meshes, and pass the mesh before and after downsampling to the `__init__` function (v=high res mesh, orig_v=downsampled mesh). Then pass the other high-res mesh to `upsample()`, it will return the downsampled mesh.

Thanks for your quick reply!

**Comment by jinmelo** [comment]
> 

I just tried with Mixamo data, so all the downsampled meshes should share the same faces with the first downsampled mesh, right?  But the resulting other downsampled meshes seem to have wrong faces like this(before and after downsampled):
<img width="260" alt="image" src="https://user-images.githubusercontent.com/53347259/201153819-39c17789-720a-4a07-9274-dc57b5ec7ac3.png">
<img width="339" alt="image" src="https://user-images.githubusercontent.com/53347259/201153874-0d8eedee-b397-4724-b170-2e01b875da1d.png">
