### ISSUE TITLE
About training dataset details.

### ISSUE THREAD

**Issue by twowwj** [zycliao/skeleton-free-pose-transfer#6]
Hi,
I would like to try to reproduce the results in the paper, the details about the division of mixamo are in the supplementary material, so far I have not found the supplementary material, could you provide it to me?
Also, in the Rignet, you remove the poses that cannot be driven by the human body.
I would like to know exactly which pose you deleted. if possible, could you give me a list of the deleted pose files? I would like to reproduce it as soon as possible.

Thanks~

**Comment by zycliao** [comment]
There are the names of models in RigNet that we used.

[humanoid_train_new.txt](https://github.com/zycliao/skeleton-free-pose-transfer/files/9601894/humanoid_train_new.txt)
[humanoid_test_new.txt](https://github.com/zycliao/skeleton-free-pose-transfer/files/9601895/humanoid_test_new.txt)

**Comment by twowwj** [comment]
thx, that's what I needed!

**Comment by MaryP111** [comment]
Could you please also provide the division of Mixamo dataset? I didn't manage to find the supplementary material anywhere.
