### ISSUE TITLE
Settings for the bvh file in data preprocessing

### ISSUE THREAD

**Issue by sunshineatnoon** [zycliao/skeleton-free-pose-transfer#9]
Hi, Thanks for open sourcing the project.

Following the [data pre-process instruction](https://github.com/zycliao/skeleton-free-pose-transfer#mixamo), I can get the skinning weight and T-pose mesh, but I cannot correctly deform the mesh using the bvh files. I was wondering if there is any specific setting needed for this process, e.g. eular axis order

Specifically, this is my mesh (`v0_1`) and joints (`joings0_1`) before calling [lbs](https://github.com/zycliao/skeleton-free-pose-transfer/blob/main/data_utils/mixamo_loader.py#L276) (red points are joints)
![snapshot00](https://user-images.githubusercontent.com/7546747/197081509-2cc479db-6d71-47b5-bda7-cc744342ae65.png)

This is what the deformed mesh (`v1`) and joints (`joints1`) look like:
![snapshot00](https://user-images.githubusercontent.com/7546747/197081648-8808aa27-3435-4d37-8174-19d5b3e28fdb.png)

While the pose in the bvh is 

![Screenshot from 2022-10-20 17-08-20](https://user-images.githubusercontent.com/7546747/197082009-1eda36f7-ec98-4e7d-869a-448044b638f4.png)

I use Blender to convert the fbx downloaded from Mixamo to bvh like this:

![Screenshot from 2022-10-20 17-13-06](https://user-images.githubusercontent.com/7546747/197082453-611da9dd-99ab-438e-b8ee-80e073198287.png)

I feel the skinning weights are correct based on the visualization, but there might be something wrong with the motion file exported from bvh, so could you please let me know how to get the bvh file correctly? Thanks

**Comment by mackery** [comment]
Hope you're doing well! 👋 I was wondering if you'd be open to sharing the source code for the OBJ to BVH conversion. It would be a huge help for my project!Totally understand if it's not something you're comfortable with. Either way, big thanks for your cool work!
